### ISSUE TITLE
Bug: Persisting events after restoring fails (Postgresql Plugin)

### ISSUE THREAD

**Issue by ncthbrt** [ncthbrt/nact#7]
Steps to Reproduce:
1. Create a persistent actor
2. Persist a few events
3. Restart program
4. Rehydrate actor with the same persistent key
5. Attempt to persist a new event 

This produces the following error message:

```
"error: duplicate key value violates unique constraint \"event_journal_uq\"
    at Connection.parseE (/Users/nick/root_bank/root-platform/service.insurance.claims/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/nick/root_bank/root-platform/service.insurance.claims/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/nick/root_bank/root-platform/service.insurance.claims/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)"
```

**Comment by ncthbrt** [comment]
Fixed in v2.0.2
